import assert from "node:assert/strict";
import { randomBytes, scrypt as scryptCallback } from "node:crypto";
import test from "node:test";
function scrypt(password: string, salt: Buffer): Promise<Buffer> { return new Promise((resolve, reject) => scryptCallback(password, salt, 64, { N: 16384, r: 8, p: 1, maxmem: 32 * 1024 * 1024 }, (error, derived) => error ? reject(error) : resolve(derived))); }
// @ts-expect-error TypeScript's bundler resolver intentionally disallows this extension.
const auth = await import("../lib/admin-auth.ts");
const env = process.env as Record<string, string | undefined>, oldHash = env.VCOBS_ADMIN_PASSWORD_HASH, oldSecret = env.VCOBS_ADMIN_SESSION_SECRET, oldEnv = env.NODE_ENV, oldTrustProxy = env.VCOBS_TRUST_PROXY_HEADERS, oldPublicOrigin = env.VCOBS_PUBLIC_ORIGIN;
async function configure(password = "correct horse battery staple") { const salt = randomBytes(16); const hash = await scrypt(password, salt); env.VCOBS_ADMIN_PASSWORD_HASH = `scrypt$16384$8$1$${salt.toString("base64")}$${hash.toString("base64")}`; env.VCOBS_ADMIN_SESSION_SECRET = randomBytes(48).toString("base64"); }
test.after(() => { oldHash === undefined ? delete env.VCOBS_ADMIN_PASSWORD_HASH : env.VCOBS_ADMIN_PASSWORD_HASH = oldHash; oldSecret === undefined ? delete env.VCOBS_ADMIN_SESSION_SECRET : env.VCOBS_ADMIN_SESSION_SECRET = oldSecret; oldEnv === undefined ? delete env.NODE_ENV : env.NODE_ENV = oldEnv; oldTrustProxy === undefined ? delete env.VCOBS_TRUST_PROXY_HEADERS : env.VCOBS_TRUST_PROXY_HEADERS = oldTrustProxy; oldPublicOrigin === undefined ? delete env.VCOBS_PUBLIC_ORIGIN : env.VCOBS_PUBLIC_ORIGIN = oldPublicOrigin; });
test("password verification accepts only matching scrypt password and fails closed", async () => { delete process.env.VCOBS_ADMIN_PASSWORD_HASH; delete process.env.VCOBS_ADMIN_SESSION_SECRET; assert.equal(auth.adminAuthConfigured(), false); assert.equal(await auth.verifyAdminPassword("anything"), false); await configure(); assert.equal(auth.adminAuthConfigured(), true); assert.equal(await auth.verifyAdminPassword("correct horse battery staple"), true); assert.equal(await auth.verifyAdminPassword("incorrect"), false); });
test("signed sessions reject expiration and tampering", async () => { await configure(); const now = 1_700_000_000_000, token = auth.createAdminSession(now); assert.ok(token); assert.equal(auth.validateAdminSession(token, now + 1), true); assert.equal(auth.validateAdminSession(token, now + 8 * 60 * 60 * 1000), false); assert.equal(auth.validateAdminSession(`${token}x`, now + 1), false); });
test("session cookie has secure production attributes", () => { env.NODE_ENV = "production"; const cookie = auth.adminSessionCookie("token"); assert.equal(cookie.httpOnly, true); assert.equal(cookie.sameSite, "strict"); assert.equal(cookie.secure, true); assert.equal(cookie.path, "/"); assert.ok(cookie.maxAge > 0); assert.equal(auth.expiredAdminSessionCookie().maxAge, 0); });
test("origin checks reject absent, cross-site, and cross-scheme origins", () => { delete env.VCOBS_TRUST_PROXY_HEADERS; assert.equal(auth.originIsSameSite(new Request("https://vcobs.example/api/admin/login")), false); assert.equal(auth.originIsSameSite(new Request("https://vcobs.example/api/admin/login", { headers: { origin: "https://evil.example" } })), false); assert.equal(auth.originIsSameSite(new Request("https://vcobs.example/api/admin/login", { headers: { origin: "http://vcobs.example" } })), false); assert.equal(auth.originIsSameSite(new Request("https://vcobs.example/api/admin/login", { headers: { origin: "https://vcobs.example" } })), true); });
test("proxy headers are ignored unless explicitly trusted", () => { const request = new Request("http://app:3080/api/admin/login", { headers: { origin: "https://vcobs.example", "x-forwarded-host": "vcobs.example", "x-forwarded-proto": "https", "x-forwarded-for": "203.0.113.4" } }); delete env.VCOBS_TRUST_PROXY_HEADERS; assert.equal(auth.originIsSameSite(request), false); assert.equal(auth.loginClientId(request), "shared"); env.VCOBS_TRUST_PROXY_HEADERS = "true"; env.VCOBS_PUBLIC_ORIGIN = "https://vcobs.example"; assert.equal(auth.originIsSameSite(request), true); assert.equal(auth.loginClientId(request), "proxy:203.0.113.4"); });
test("trusted proxy origin must match configured canonical public origin", () => { const request = new Request("https://0.0.0.0:3080/api/admin/login", { headers: { "x-forwarded-host": "vcobs.example", "x-forwarded-proto": "https" } }); delete env.VCOBS_TRUST_PROXY_HEADERS; assert.equal(auth.publicRequestOrigin(request), "https://0.0.0.0:3080"); env.VCOBS_TRUST_PROXY_HEADERS = "true"; delete env.VCOBS_PUBLIC_ORIGIN; assert.equal(auth.publicRequestOrigin(request), null); env.VCOBS_PUBLIC_ORIGIN = "https://vcobs.example"; assert.equal(auth.publicRequestOrigin(request), "https://vcobs.example"); const evil = new Request("https://0.0.0.0:3080/api/admin/login", { headers: { "x-forwarded-host": "evil.example", "x-forwarded-proto": "https" } }); assert.equal(auth.publicRequestOrigin(evil), null); env.VCOBS_PUBLIC_ORIGIN = "https://vcobs.example/path"; assert.equal(auth.publicRequestOrigin(request), null); });
test("rate limit resists spoofed forwarded IPs and has a global bound", () => { auth.resetLoginRateLimitsForTests(); delete env.VCOBS_TRUST_PROXY_HEADERS; for (let index = 0; index < 5; index++) { const request = new Request("http://app/login", { headers: { "x-forwarded-for": `198.51.100.${index}` } }); const client = auth.loginClientId(request); assert.equal(client, "shared"); assert.equal(auth.loginAllowed(client), true); auth.recordFailedLogin(client); } assert.equal(auth.loginAllowed("shared"), false); auth.resetLoginRateLimitsForTests(); env.VCOBS_TRUST_PROXY_HEADERS = "true"; for (let index = 0; index < 50; index++) auth.recordFailedLogin(`proxy:203.0.113.${index}`); assert.equal(auth.loginAllowed("proxy:203.0.113.250"), false); });
